### PR TITLE
Add textStyles to tables

### LINKED ISSUE #29: Have text style formatting for tables
If there are text styles (italic, bold, etc.) in a table, those styles shouldn't be stripped in the final html.

### PR DESCRIPTION
**Pull request by justinsunho**
fixes #29

So that users can style text in tables and have those styles reflected in the final markup.

### CODE REVIEW

**Comment by justinsunho** [comment]
@xuopled any plans to take a look at this?

**Comment by xuopled** [comment]
Thank you @justinsunho for your work

**Comment by xuopled** [comment]
Sorry for the delay

**Comment by xuopled** [comment]
Published in `v1.14.0`

**Pull request merged**
