### PR TITLE
Feature/parse advavanced doc formatting

### PR DESCRIPTION
**Pull request by horaklukas**
* Add support for correct displaying of
  * nested lists
  * ordered lists
  * inline links
* Fix putting list items into the list they belong to
* Fix splitting one line headings or texts into more lines

### CODE REVIEW

**Comment by horaklukas** [comment]
I thought it 🙂 sadly I haven't permission to assignee you to PR, which would do the notification. Ok, I'll do my best.

**Comment by xuopled** [comment]
I'm watching now so I can merge it and release it quickly 🙂

**Comment by horaklukas** [comment]
Ok, I'm sorry I was quite busy yesterday thus I didn't make it. I would do it today but you've been faster 👍

**Comment by xuopled** [comment]
No problem. I could make it from Github directly. I just published `v1.1.0`.

Thank you again for your help !

Feel free to open other PRs to make this plugin better 💪🏻

**Pull request merged**
